name: Stable release
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name : version
      run: echo "::set-output name=version::$(cat version)" 
      id: version
 
    - name: build
      run: ./lit -f styles.env

    - name: rename build
      run: mv dist/bubble.ui.css dist/bubble.ui-v${{ steps.version.outputs.version }}.css

    - name: Create a Release of commit
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: ${{ github.token }}
        automatic_release_tag: v${{ steps.version.outputs.version }}
        prerelease: false
        title: ${{ steps.version.outputs.version }} 
        files: |
          LICENSE
          dist/*.css
